import{createClient}from'https://esm.sh/@neondatabase/neon-js@0.7.0-beta?bundle';
const VERSION='0.27.4';
const C=createClient({auth:{url:'https://ep-solitary-haze-b1lmo06g.neonauth.c-5.eu-central-1.aws.neon.tech/neondb/auth'},dataApi:{url:'https://ep-solitary-haze-b1lmo06g.apirest.c-5.eu-central-1.aws.neon.tech/neondb/rest/v1'}});
window.NovaCallAccountClient=C;
const $=s=>document.querySelector(s),make=(t,c)=>{const e=document.createElement(t);if(c)e.className=c;return e};
let user=null,profile=null,guest=false;
const css=make('style');css.textContent=`
.nc-auth-gate{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;padding:20px;background:radial-gradient(900px 600px at 50% -10%,rgba(80,226,184,.18),transparent 58%),rgba(3,8,13,.97);backdrop-filter:blur(22px)}
.nc-auth-card{width:min(440px,94vw);padding:24px;border-radius:28px;border:1px solid rgba(126,164,183,.2);background:linear-gradient(180deg,rgba(17,27,43,.98),rgba(7,13,22,.99));box-shadow:0 34px 110px rgba(0,0,0,.55);color:#f7f9fc}.nc-auth-head{display:flex;align-items:center;gap:12px;margin-bottom:16px}.nc-auth-logo{width:50px;height:50px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(135deg,#43dbaa,#3dbbd2);font-size:22px;font-weight:950;box-shadow:0 14px 38px rgba(61,187,210,.25)}.nc-auth-title{font-size:20px;font-weight:950;letter-spacing:-.03em}.nc-auth-sub{font-size:10px;color:#8995a9;margin-top:2px}.nc-auth-tabs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:14px 0}.nc-auth-tabs button{height:42px;border:1px solid #29364e;border-radius:12px;background:#111a2a;color:#9ba7b8;font-weight:850}.nc-auth-tabs button.on{background:linear-gradient(135deg,#43dbaa,#3dbbd2);border-color:transparent;color:#06130f}.nc-auth-field{display:grid;gap:6px;margin:10px 0}.nc-auth-field label{font-size:8px;font-weight:950;letter-spacing:.13em;color:#8794a8}.nc-auth-field input{height:44px;border-radius:12px;border:1px solid #2b3850;background:#080e18;color:#fff;padding:0 12px;outline:none}.nc-auth-field input:focus{border-color:#49d6bc;box-shadow:0 0 0 4px rgba(73,214,188,.09)}.nc-auth-main{width:100%;height:44px;border:0;border-radius:12px;background:linear-gradient(135deg,#43dbaa,#3dbbd2);color:#06130f;font-weight:950;margin-top:5px}.nc-auth-guest{width:100%;border:0;background:none;color:#7e899b;padding:11px;cursor:pointer}.nc-auth-err{min-height:18px;padding-top:7px;color:#ff8fa2;font-size:10px}.nc-auth-note{font-size:9px;line-height:1.5;color:#758196;margin-top:8px}.nc-account-strip{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:9px;align-items:center;padding:9px;margin:13px 0;border:1px solid rgba(120,150,180,.18);border-radius:14px;background:linear-gradient(145deg,rgba(17,28,45,.88),rgba(8,14,24,.88))}.nc-account-av{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,#43dbaa,#3dbbd2);color:#07140f;font-weight:950}.nc-account-main{min-width:0}.nc-account-main b,.nc-account-main span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nc-account-main b{font-size:10px}.nc-account-main span{font-size:8px;color:#7f8b9f;margin-top:2px}.nc-account-strip button{height:30px;padding:0 9px;border:1px solid #2b3850;border-radius:9px;background:#121b2b;color:#c9d1df;font-size:8px;font-weight:850}`;document.head.appendChild(css);
function initials(n){return(String(n||'?').trim()[0]||'?').toUpperCase()}function msg(e){return String(e?.message||e?.error?.message||e||'Erreur')}function reveal(){document.documentElement.classList.remove('nc-auth-boot')}
async function getProfile(id){const{data,error}=await C.from('novacall_accounts').select('*').eq('user_id',id).limit(1);if(error)throw error;return data?.[0]||null}async function createProfile(name){name=String(name||'').trim();if(!/^[A-Za-z0-9_.-]{3,24}$/.test(name))throw Error('Pseudo : 3 à 24 caractères, lettres/chiffres/._-');const{data,error}=await C.from('novacall_accounts').insert({username:name}).select('*');if(error)throw error;return data?.[0]||null}
function fillName(){const n=$('#name');if(n&&profile?.username){n.value=profile.username;try{localStorage.setItem('novacall-name-v027',profile.username)}catch{}}}
function strip(){const side=$('.sidebar');if(!side)return;side.querySelector('.nc-account-strip')?.remove();const b=make('div','nc-account-strip');b.innerHTML='<div class="nc-account-av"></div><div class="nc-account-main"><b></b><span></span></div><button type="button"></button>';b.querySelector('.nc-account-av').textContent=initials(profile?.username||'G');b.querySelector('b').textContent=profile?.username||'Mode invité';b.querySelector('span').textContent=profile?'Compte NovaCall':'Session invitée';const bt=b.querySelector('button');bt.textContent=profile?'Déconnexion':'Connexion';bt.onclick=async()=>{if(profile){try{await C.auth.signOut()}catch{}location.href=location.origin}else location.reload()};const anchor=side.querySelector('.room-box');if(anchor)anchor.insertAdjacentElement('beforebegin',b);else side.appendChild(b)}
function activate(p){profile=p;fillName();strip();reveal()}
function gate(profileOnly=false){document.querySelector('.nc-auth-gate')?.remove();const g=make('div','nc-auth-gate');g.innerHTML=profileOnly?`<div class="nc-auth-card"><div class="nc-auth-head"><div class="nc-auth-logo">N</div><div><div class="nc-auth-title">Finalise ton compte NovaCall</div><div class="nc-auth-sub">Choisis ton pseudo NovaCall.</div></div></div><div class="nc-auth-field"><label>PSEUDO NOVACALL</label><input id="ncAuthUsername" maxlength="24" placeholder="Ton pseudo"></div><button type="button" class="nc-auth-main" id="ncAuthProfile">Créer mon profil</button><div class="nc-auth-err" id="ncAuthErr"></div></div>`:`<div class="nc-auth-card"><div class="nc-auth-head"><div class="nc-auth-logo">N</div><div><div class="nc-auth-title">Ton compte NovaCall</div><div class="nc-auth-sub">Retrouve ton profil sur tous tes appareils.</div></div></div><div class="nc-auth-tabs"><button type="button" class="on" data-mode="login">Connexion</button><button type="button" data-mode="signup">Créer un compte</button></div><div class="nc-auth-field nc-auth-user" style="display:none"><label>PSEUDO NOVACALL</label><input id="ncAuthUsername" maxlength="24" placeholder="Ton pseudo"></div><div class="nc-auth-field"><label>EMAIL</label><input id="ncAuthEmail" type="email" autocomplete="email" placeholder="toi@email.com"></div><div class="nc-auth-field"><label>MOT DE PASSE</label><input id="ncAuthPassword" type="password" autocomplete="current-password" placeholder="8 caractères minimum"></div><button type="button" class="nc-auth-main" id="ncAuthSubmit">Se connecter</button><div class="nc-auth-err" id="ncAuthErr"></div><button type="button" class="nc-auth-guest" id="ncAuthGuest">Continuer en invité</button><div class="nc-auth-note">Ta session reste enregistrée sur cet appareil.</div></div>`;document.body.appendChild(g);const err=g.querySelector('#ncAuthErr');if(profileOnly){g.querySelector('#ncAuthProfile').onclick=async()=>{const b=g.querySelector('#ncAuthProfile'),name=g.querySelector('#ncAuthUsername').value.trim();b.disabled=true;err.textContent='';try{activate(await createProfile(name));g.remove()}catch(e){err.textContent=msg(e)}finally{b.disabled=false}};return}
let mode='login';const tabs=[...g.querySelectorAll('[data-mode]')],userRow=g.querySelector('.nc-auth-user'),submit=g.querySelector('#ncAuthSubmit');tabs.forEach(b=>b.onclick=()=>{mode=b.dataset.mode;tabs.forEach(x=>x.classList.toggle('on',x===b));userRow.style.display=mode==='signup'?'grid':'none';submit.textContent=mode==='signup'?'Créer mon compte':'Se connecter';g.querySelector('#ncAuthPassword').autocomplete=mode==='signup'?'new-password':'current-password';err.textContent=''});g.querySelector('#ncAuthGuest').onclick=()=>{guest=true;g.remove();strip();reveal()};submit.onclick=async()=>{const email=g.querySelector('#ncAuthEmail').value.trim(),password=g.querySelector('#ncAuthPassword').value,name=g.querySelector('#ncAuthUsername').value.trim();if(!email||!password){err.textContent='Entre ton email et ton mot de passe.';return}if(mode==='signup'&&!name){err.textContent='Choisis aussi ton pseudo NovaCall.';return}submit.disabled=true;err.textContent='';try{const r=mode==='signup'?await C.auth.signUp.email({email,password,name}):await C.auth.signIn.email({email,password,rememberMe:true});if(r?.error)throw r.error;user=r?.data?.user||r?.data?.session?.user||null;if(!user)throw Error('Session non créée. Réessaie.');let p=await getProfile(user.id);if(!p&&mode==='signup')p=await createProfile(name);if(!p){g.remove();gate(true);return}activate(p);g.remove()}catch(e){err.textContent=msg(e)}finally{submit.disabled=false}}}
async function boot(){document.title='NovaCall V'+VERSION;try{const r=await C.auth.getSession();user=r?.data?.user||r?.data?.session?.user||null;if(user){const p=await getProfile(user.id);if(p){activate(p);return}gate(true);return}}catch(e){console.warn('NovaCall account',e)}gate(false)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
