import{createClient}from'https://esm.sh/@neondatabase/neon-js@0.7.0-beta?bundle';

const VERSION='0.27.4';
const C=createClient({auth:{url:'https://ep-solitary-haze-b1lmo06g.neonauth.c-5.eu-central-1.aws.neon.tech/neondb/auth'},dataApi:{url:'https://ep-solitary-haze-b1lmo06g.apirest.c-5.eu-central-1.aws.neon.tech/neondb/rest/v1'}});
window.NovaCallAccountClient=C;

const $=s=>document.querySelector(s);
const el=(t,c)=>{const e=document.createElement(t);if(c)e.className=c;return e};
let currentUser=null,currentProfile=null,guest=false;

const style=el('style');
style.textContent=`
.nc-auth-gate{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;padding:20px;background:radial-gradient(900px 600px at 50% -10%,rgba(80,226,184,.18),transparent 58%),rgba(3,8,13,.965);backdrop-filter:blur(22px)}
.nc-auth-card{width:min(440px,94vw);padding:24px;border-radius:28px;border:1px solid rgba(126,164,183,.2);background:linear-gradient(180deg,rgba(17,27,43,.98),rgba(7,13,22,.99));box-shadow:0 34px 110px rgba(0,0,0,.55);color:#f7f9fc}
.nc-auth-head{display:flex;align-items:center;gap:12px;margin-bottom:16px}.nc-auth-logo{width:50px;height:50px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(135deg,#43dbaa,#3dbbd2);font-size:22px;font-weight:950;box-shadow:0 14px 38px rgba(61,187,210,.25)}
.nc-auth-title{font-size:20px;font-weight:950;letter-spacing:-.03em}.nc-auth-sub{font-size:10px;color:#8995a9;margin-top:2px}
.nc-auth-tabs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:14px 0}.nc-auth-tabs button{height:42px;border:1px solid #29364e;border-radius:12px;background:#111a2a;color:#9ba7b8;font-weight:850}.nc-auth-tabs button.on{background:linear-gradient(135deg,#43dbaa,#3dbbd2);border-color:transparent;color:#06130f}
.nc-auth-field{display:grid;gap:6px;margin:10px 0}.nc-auth-field label{font-size:8px;font-weight:950;letter-spacing:.13em;color:#8794a8}.nc-auth-field input{height:44px;border-radius:12px;border:1px solid #2b3850;background:#080e18;color:#fff;padding:0 12px;outline:none}.nc-auth-field input:focus{border-color:#49d6bc;box-shadow:0 0 0 4px rgba(73,214,188,.09)}
.nc-auth-main{width:100%;height:44px;border:0;border-radius:12px;background:linear-gradient(135deg,#43dbaa,#3dbbd2);color:#06130f;font-weight:950;margin-top:5px}.nc-auth-guest{width:100%;border:0;background:none;color:#7e899b;padding:11px;cursor:pointer}.nc-auth-err{min-height:18px;padding-top:7px;color:#ff8fa2;font-size:10px}.nc-auth-note{font-size:9px;line-height:1.5;color:#758196;margin-top:8px}
.nc-account-strip{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:9px;align-items:center;padding:9px;margin:13px 0;border:1px solid rgba(120,150,180,.18);border-radius:14px;background:linear-gradient(145deg,rgba(17,28,45,.88),rgba(8,14,24,.88))}.nc-account-av{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,#43dbaa,#3dbbd2);color:#07140f;font-weight:950}.nc-account-main{min-width:0}.nc-account-main b,.nc-account-main span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nc-account-main b{font-size:10px}.nc-account-main span{font-size:8px;color:#7f8b9f;margin-top:2px}.nc-account-strip button{height:30px;padding:0 9px;border:1px solid #2b3850;border-radius:9px;background:#121b2b;color:#c9d1df;font-size:8px;font-weight:850}
`;
document.head.appendChild(style);

function initials(n){return(String(n||'?').trim()[0]||'?').toUpperCase()}
function messageOf(e){return String(e?.message||e?.error?.message||e||'Erreur')}
async function profileFor(id){const{data,error}=await C.from('novacall_accounts').select('*').eq('user_id',id).limit(1);if(error)throw error;return data?.[0]||null}
async function createProfile(username){username=String(username||'').trim();if(!/^[A-Za-z0-9_.-]{3,24}$/.test(username))throw Error('Pseudo : 3 à 24 caractères, lettres/chiffres/._-');const{data,error}=await C.from('novacall_accounts').insert({username}).select('*');if(error)throw error;return data?.[0]||null}

function revealJoin(){document.documentElement.classList.remove('nc-auth-boot')}
function fillName(){const input=$('#name');if(input&&currentProfile?.username){input.value=currentProfile.username;try{localStorage.setItem('novacall-name-v027',currentProfile.username)}catch{}}}
function mountAccountStrip(){const side=$('.sidebar');if(!side)return;side.querySelector('.nc-account-strip')?.remove();const box=el('div','nc-account-strip');box.innerHTML='<div class="nc-account-av"></div><div class="nc-account-main"><b></b><span></span></div><button type="button"></button>';box.querySelector('.nc-account-av').textContent=initials(currentProfile?.username||'G');box.querySelector('.nc-account-main b').textContent=currentProfile?.username||'Mode invité';box.querySelector('.nc-account-main span').textContent=currentProfile?'Compte NovaCall':'Session invitée';const btn=box.querySelector('button');btn.textContent=currentProfile?'Déconnexion':'Connexion';btn.onclick=async()=>{if(currentProfile){try{await C.auth.signOut()}catch{}location.href=location.origin}else location.reload()};const anchor=side.querySelector('.room-box');if(anchor)anchor.insertAdjacentElement('beforebegin',box);else side.appendChild(box)}

async function finish(user){currentUser=user;currentProfile=await profileFor(user.id);if(!currentProfile)return false;fillName();revealJoin();mountAccountStrip();return true}

function buildGate(){document.querySelector('.nc-auth-gate')?.remove();const gate=el('div','nc-auth-gate');gate.innerHTML=`<div class="nc-auth-card"><div class="nc-auth-head"><div class="nc-auth-logo">N</div><div><div class="nc-auth-title">Ton compte NovaCall</div><div class="nc-auth-sub">Connecte-toi ou crée ton compte pour retrouver ton profil.</div></div></div><div class="nc-auth-tabs"><button type="button" class="on" data-mode="login">Connexion</button><button type="button" data-mode="signup">Créer un compte</button></div><div class="nc-auth-field nc-auth-user" style="display:none"><label>PSEUDO NOVACALL</label><input id="ncAuthUsername" maxlength="24" placeholder="Ton pseudo"></div><div class="nc-auth-field"><label>EMAIL</label><input id="ncAuthEmail" type="email" autocomplete="email" placeholder="toi@email.com"></div><div class="nc-auth-field"><label>MOT DE PASSE</label><input id="ncAuthPassword" type="password" autocomplete="current-password" placeholder="8 caractères minimum"></div><button type="button" class="nc-auth-main" id="ncAuthSubmit">Se connecter</button><div class="nc-auth-err" id="ncAuthErr"></div><button type="button" class="nc-auth-guest" id="ncAuthGuest">Continuer en invité</button><div class="nc-auth-note">Ta session reste enregistrée sur cet appareil quand tu te connectes.</div></div>`;document.body.appendChild(gate);
 let mode='login';const tabs=[...gate.querySelectorAll('[data-mode]')],userRow=gate.querySelector('.nc-auth-user'),submit=gate.querySelector('#ncAuthSubmit'),err=gate.querySelector('#ncAuthErr');
 tabs.forEach(b=>b.onclick=()=>{mode=b.dataset.mode;tabs.forEach(x=>x.classList.toggle('on',x===b));userRow.style.display=mode==='signup'?'grid':'none';submit.textContent=mode==='signup'?'Créer mon compte':'Se connecter';gate.querySelector('#ncAuthPassword').autocomplete=mode==='signup'?'new-password':'current-password';err.textContent=''});
 gate.querySelector('#ncAuthGuest').onclick=()=>{guest=true;gate.remove();revealJoin();mountAccountStrip()};
 submit.onclick=async()=>{const email=gate.querySelector('#ncAuthEmail').value.trim(),password=gate.querySelector('#ncAuthPassword').value,username=gate.querySelector('#ncAuthUsername').value.trim();if(!email||!password){err.textContent='Entre ton email et ton mot de passe.';return}if(mode==='signup'&&!username){err.textContent='Choisis aussi ton pseudo NovaCall.';return}submit.disabled=true;err.textContent='';try{const r=mode==='signup'?await C.auth.signUp.email({email,password,name:username}):await C.auth.signIn.email({email,password,rememberMe:true});if(r?.error)throw r.error;const user=r?.data?.user||r?.data?.session?.user;if(!user)throw Error('Session non créée. Réessaie.');currentUser=user;let p=await profileFor(user.id);if(!p&&mode==='signup')p=await createProfile(username);if(!p){err.textContent='Compte connecté, mais aucun profil NovaCall. Choisis un pseudo.';userRow.style.display='grid';submit.textContent='Créer mon profil';mode='profile';submit.disabled=false;return}currentProfile=p;fillName();gate.remove();revealJoin();mountAccountStrip()}catch(e){if(mode==='profile'){try{currentProfile=await createProfile(username);fillName();gate.remove();revealJoin();mountAccountStrip()}catch(x){err.textContent=messageOf(x)}}else err.textContent=messageOf(e)}finally{submit.disabled=false}};
}

async function boot(){document.title='NovaCall V'+VERSION;try{const r=await C.auth.getSession();const user=r?.data?.user||r?.data?.session?.user||null;if(user){const ok=await finish(user);if(ok)return}}catch(e){console.warn('NovaCall account session',e)}buildGate()}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
setInterval(()=>{if(currentProfile||guest)mountAccountStrip()},1500);
