(()=>{'use strict';
const $=id=>document.getElementById(id),SIGNAL_URL='wss://0.peerjs.com/peerjs',SIGNAL_VERSION='1.5.5',ICE=[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}],READ=4194304;
let ws=null,pc=null,ch=null,sender='',cid='',pending=[],batch=null,current=null,received=0,totalReceived=0,base=0,started=0,writer=null,chain=Promise.resolve(),opfs=null,dir=null,single=null,handles=new Map(),urls=[],results=[],accepted=false,finished=false,retry=null,retries=0,wake=null,crc=0xffffffff,storage='en attente';
const table=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);t[n]=c>>>0}return t})();
const crcUp=(c,u)=>{for(let i=0;i<u.length;i++)c=table[(c^u[i])&255]^(c>>>8);return c>>>0},crcHex=c=>((c^0xffffffff)>>>0).toString(16).padStart(8,'0');
async function crcPrefix(file,limit){let c=0xffffffff,o=0,m=Math.min(Number(limit)||0,file.size);while(o<m){const e=Math.min(o+READ,m),b=await file.slice(o,e).arrayBuffer();c=crcUp(c,new Uint8Array(b));o=e}return c>>>0}
function rid(p='nova-file'){const a=new Uint8Array(18);crypto.getRandomValues(a);return p+'-'+Array.from(a,b=>b.toString(16).padStart(2,'0')).join('')}
function fmt(b){const u=['B','KB','MB','GB','TB'];let i=0,n=Number(b)||0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?2:0)+' '+u[i]}
function safe(n){return(n||'nova-file').replace(/[\\/:*?"<>|]/g,'_')}
function ext(n){const p=(n||'').split('.');return(p.length>1?p.pop():'FILE').toUpperCase().slice(0,6)}
function stat(k,t,d){$('statusDot').className='dot'+(k==='ok'?' ok':k==='err'?' err':'');$('statusTitle').textContent=t;$('statusDetail').textContent=d||''}
function guard(on,text=''){$('guard').classList.toggle('hidden',!on);if(text)$('guardText').textContent=text}
function conn(){return navigator.connection||navigator.mozConnection||navigator.webkitConnection||null}
function mobile(){const t=String(conn()?.type||conn()?.connectionType||'').toLowerCase(),c=t==='cellular'||t==='cell'||t==='mobile'||t.includes('cellular');$('mobileNotice').classList.toggle('hidden',!c)}
function ui(){$('storageMode').textContent='STOCKAGE · '+storage;$('wakeMode').textContent='ÉCRAN · '+(wake?'maintenu actif':('wakeLock'in navigator?'prêt':'non supporté'))}
async function wakeOn(){if(!('wakeLock'in navigator)||document.visibilityState!=='visible'){ui();return}try{if(wake&&!wake.released)return;wake=await navigator.wakeLock.request('screen');wake.addEventListener('release',()=>{wake=null;ui()},{once:true});ui()}catch{wake=null;ui()}}
async function wakeOff(){try{await wake?.release()}catch{}wake=null;ui()}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&accepted&&!finished)wakeOn()});
function sendSig(type,dst,payload){if(ws?.readyState!==1)throw new Error('Signalisation non connectée.');ws.send(JSON.stringify({type,dst,payload}))}
function closeSig(){try{ws?.close()}catch{}ws=null}
function openSig(id){return new Promise((resolve,reject)=>{closeSig();const token=Math.random().toString(36).slice(2)+Date.now().toString(36);ws=new WebSocket(`${SIGNAL_URL}?key=peerjs&id=${encodeURIComponent(id)}&token=${encodeURIComponent(token)}&version=${SIGNAL_VERSION}`);let opened=false,done=false,hb=null;const fail=m=>{if(!done){done=true;reject(new Error(m))}};ws.addEventListener('open',()=>{hb=setInterval(()=>{if(ws.readyState===1)ws.send(JSON.stringify({type:'HEARTBEAT'}))},5000)});ws.addEventListener('message',async e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='OPEN'){opened=true;if(!done){done=true;resolve()}return}if(m.type==='ANSWER'){if(!pc||m.payload?.connectionId!==cid)return;await pc.setRemoteDescription(m.payload.sdp);await flush();return}if(m.type==='CANDIDATE'){if(cid&&m.payload?.connectionId&&m.payload.connectionId!==cid)return;const c=m.payload?.candidate;if(!c)return;if(pc?.remoteDescription){try{await pc.addIceCandidate(c)}catch{}}else pending.push(c);return}if(m.type==='EXPIRE')stat('err','QR expiré','Retourne sur le PC et recrée un QR.');if(m.type==='ERROR')stat('err','Connexion impossible',m.payload?.msg||'Erreur de signalisation.')});ws.addEventListener('error',()=>fail('Le service de connexion est indisponible.'));ws.addEventListener('close',()=>{if(hb)clearInterval(hb);if(accepted&&!finished)scheduleRetry()});setTimeout(()=>{if(!opened&&!done){try{ws.close()}catch{}fail('Le serveur ne répond pas.')}},9000)})}
async function flush(){if(!pc?.remoteDescription)return;for(const c of pending.splice(0)){try{await pc.addIceCandidate(c)}catch{}}}
async function pauseWriter(){try{await chain;if(writer){await writer.close();writer=null}}catch{}chain=Promise.resolve()}
function scheduleRetry(){if(!accepted||finished||retry||retries>=10)return;retry=setTimeout(()=>{retry=null;retries++;stat('',`Reconnexion ${retries}/10…`,'NOVA conserve la progression.');connect(true).catch(()=>scheduleRetry())},1500*Math.min(5,retries+1))}
function setupChannel(c){ch=c;ch.binaryType='arraybuffer';ch.addEventListener('open',()=>{retries=0;stat('ok','Appareils connectés','Connexion P2P Ultra Large prête.')});ch.addEventListener('close',()=>{if(accepted&&!finished){pauseWriter();guard(true,'Connexion interrompue : garde les deux appareils ouverts. NOVA tente de reprendre.');stat('err','Connexion interrompue','Progression conservée. Reconnexion automatique…');scheduleRetry()}});ch.addEventListener('error',()=>stat('err','Erreur réseau','Le canal direct a rencontré un problème.'));ch.addEventListener('message',onMessage)}
async function connect(resume=false){const nested=location.href.match(/[?&]peer=(nova-file-[a-f0-9]{36})/i);sender=new URL(location.href).searchParams.get('peer')||location.hash.replace(/^#/,'')||(nested?nested[1]:'');if(!/^nova-file-[a-f0-9]{36}$/i.test(sender)){stat('err','QR NOVA invalide','Ce lien ne contient pas une session valide.');return}try{try{ch?.close();pc?.close()}catch{}closeSig();pending=[];stat('',resume?'Reconnexion au PC…':'Connexion au PC…',resume?'NOVA prépare la reprise.':'Aucune action nécessaire.');await openSig(rid());cid=rid('dc');pc=new RTCPeerConnection({iceServers:ICE});pc.addEventListener('icecandidate',e=>{if(e.candidate)try{sendSig('CANDIDATE',sender,{candidate:e.candidate.toJSON(),type:'data',connectionId:cid})}catch{}});pc.addEventListener('connectionstatechange',()=>{const s=pc.connectionState;if(s==='connected')stat('ok',resume?'Reconnecté au PC':'Connecté au PC',resume?'NOVA reprend au dernier octet conservé.':'Le transfert P2P est prêt.');else if(s==='connecting')stat('','Connexion directe…','NOVA négocie le meilleur chemin.');else if(['failed','disconnected'].includes(s)&&accepted&&!finished){pauseWriter();guard(true,'Connexion interrompue : ne ferme rien. NOVA tente de reprendre.');scheduleRetry()}});setupChannel(pc.createDataChannel('nova-transfer',{ordered:true}));const offer=await pc.createOffer();await pc.setLocalDescription(offer);sendSig('OFFER',sender,{sdp:pc.localDescription,type:'data',label:'nova-transfer',connectionId:cid,reliable:true,serialization:'none',metadata:{app:'NOVA Transfer Web',v:'1.1.7',resume:true}})}catch(e){stat('err','Connexion impossible',e.message||'Impossible de rejoindre le PC.');if(accepted&&!finished)scheduleRetry();throw e}}
function send(o){if(ch?.readyState==='open')ch.send(JSON.stringify(o))}
function partial(f){return`nova-v117-${sender.slice(-12)}-${f.index}-${safe(f.name).slice(0,120)}`}
function renderBatch(){if(!batch)return;$('fileBadge').textContent=batch.count===1?ext(batch.files[0].name):String(batch.count);$('fileName').textContent=batch.count===1?batch.files[0].name:`${batch.count} fichiers`;$('fileInfo').textContent=`${fmt(batch.totalSize)} · ${batch.count} fichier${batch.count>1?'s':''} · reprise + CRC32`;const box=$('fileList');box.innerHTML='';batch.files.slice(0,6).forEach(f=>{const row=document.createElement('div');row.className='file-row';row.innerHTML=`<b>${ext(f.name)}</b><div><strong></strong><small>${fmt(f.size)}</small></div>`;row.querySelector('strong').textContent=f.name;box.appendChild(row)});if(batch.files.length>6){const m=document.createElement('div');m.className='more';m.textContent=`+ ${batch.files.length-6} autres fichiers`;box.appendChild(m)}$('fileCard').classList.remove('hidden')}
async function getHandle(f){if(handles.has(f.index))return handles.get(f.index);let h=null;if(dir)h=await dir.getFileHandle(safe(f.name),{create:true});else if(single&&f.index===0)h=single;else if(opfs)h=await opfs.getFileHandle(partial(f),{create:true});if(h)handles.set(f.index,h);return h}
async function getOffsets(){const a=[];for(const f of batch.files){let n=0;try{let h=handles.get(f.index);if(!h&&opfs)h=await getHandle(f);if(h)n=Math.min((await h.getFile()).size,f.size)}catch{}a[f.index]=n}return a.map(x=>Number(x)||0)}
async function ensureSpace(rem){if(!opfs||!navigator.storage?.estimate)return;const e=await navigator.storage.estimate(),free=Math.max(0,(e.quota||0)-(e.usage||0));if(free&&rem>free*.96)throw new Error(`Espace insuffisant : ${fmt(free)} disponibles pour ${fmt(rem)} restants.`)}
async function accept(){if(!batch||ch?.readyState!=='open')return;$('accept').disabled=true;try{accepted=true;finished=false;if(!dir&&!single&&!opfs){if(batch.count>1&&'showDirectoryPicker'in window){try{dir=await showDirectoryPicker({mode:'readwrite'});storage='disque direct'}catch(e){if(e?.name==='AbortError'){accepted=false;$('accept').disabled=false;return}}}else if(batch.count===1&&'showSaveFilePicker'in window){try{single=await showSaveFilePicker({suggestedName:batch.files[0].name});storage='disque direct'}catch(e){if(e?.name==='AbortError'){accepted=false;$('accept').disabled=false;return}throw e}}if(!dir&&!single&&navigator.storage?.getDirectory){opfs=await navigator.storage.getDirectory();try{await navigator.storage.persist?.()}catch{}storage='stockage navigateur persistant'}if(!dir&&!single&&!opfs){storage='mémoire';if(batch.totalSize>943718400)throw new Error('Ce navigateur ne permet pas un stockage progressif assez sûr pour ce gros fichier.')}}const off=await getOffsets();totalReceived=off.reduce((a,b)=>a+b,0);await ensureSpace(Math.max(0,batch.totalSize-totalReceived));base=totalReceived;started=performance.now();ui();await wakeOn();guard(true,totalReceived?`Reprise prête : ${fmt(totalReceived)} déjà conservés. Garde les deux appareils ouverts.`:'Ne quitte pas cette page et ne ferme pas NOVA Transfer sur le PC jusqu’à 100 %.');$('fileCard').classList.add('hidden');$('progressCard').classList.remove('hidden');progress();send({type:'resume-ready',offsets:off});stat('ok',totalReceived?'Reprise en cours':'Réception en cours',totalReceived?`${fmt(totalReceived)} déjà conservés.`:'Écriture progressive + CRC32 actifs.')}catch(e){accepted=false;guard(false);await wakeOff();$('accept').disabled=false;stat('err','Réception impossible',e.message||'Impossible de préparer le stockage.')}}
async function beginFile(m){current=m;received=Math.max(0,Number(m.offset)||0);writer=null;chain=Promise.resolve();crc=0xffffffff;$('currentFile').textContent=`Fichier ${m.index+1}/${batch.count} · ${m.name}`;const h=await getHandle(m);m._handle=h;if(h){if(received>0){const f=await h.getFile();received=Math.min(received,f.size,m.size);crc=await crcPrefix(f,received);writer=await h.createWritable({keepExistingData:true});await writer.seek(received)}else writer=await h.createWritable()}else if(received>0)throw new Error('Impossible de reprendre sans stockage persistant.');progress()}
function progress(){if(!batch)return;const pct=Math.min(100,batch.totalSize?totalReceived/batch.totalSize*100:0);$('progressLabel').textContent=`RÉCEPTION ${current?current.index+1:0}/${batch.count}`;$('progressName').textContent=current?.name||(batch.count>1?`${batch.count} fichiers`:batch.files[0].name);$('pct').textContent=(pct<10?pct.toFixed(1):pct.toFixed(0))+'%';$('bar').style.width=pct+'%';$('bytes').textContent=`${fmt(totalReceived)} / ${fmt(batch.totalSize)}`;const sec=Math.max(.1,(performance.now()-started)/1000),sp=Math.max(0,totalReceived-base)/sec;$('speed').textContent=fmt(sp)+'/s';const rem=sp>0?(batch.totalSize-totalReceived)/sp:0;$('eta').textContent=rem>0?'~'+(rem<60?Math.ceil(rem)+' s':Math.ceil(rem/60)+' min'):'—';ui()}
async function finishFile(m){if(!current)return{ok:false};await chain;if(writer){await writer.close();writer=null}const actual=crcHex(crc),ok=received===current.size&&(!m.crc||actual.toLowerCase()===String(m.crc).toLowerCase());if(!ok){stat('err','Intégrité incorrecte',`${current.name} n’a pas passé le contrôle CRC32.`);return{ok:false,crc:actual,size:received}}let url=null,mode=storage;if(current._handle&&storage!=='disque direct'){const f=await current._handle.getFile();url=URL.createObjectURL(f);urls.push(url)}else if(!current._handle)return{ok:false,crc:actual,size:received};const item={index:current.index,name:current.name,size:received,url,mode,crc:actual};results=results.filter(r=>r.index!==item.index);results.push(item);results.sort((a,b)=>a.index-b.index);current=null;renderDownloads();return{ok:true,crc:actual,size:item.size}}
function renderDownloads(){const box=$('downloadList');box.innerHTML='';for(const r of results){const row=document.createElement('div');row.className='download-item';row.innerHTML=`<b>${ext(r.name)}</b><div><strong></strong><small>${fmt(r.size)} · ${r.mode} · CRC32 ${r.crc}</small></div>`;row.querySelector('strong').textContent=r.name;if(r.url){const a=document.createElement('a');a.href=r.url;a.download=r.name;a.textContent='Télécharger';row.appendChild(a)}box.appendChild(row)}}
async function done(){finished=true;accepted=false;guard(false);if(retry)clearTimeout(retry);$('progressCard').classList.add('hidden');$('doneName').textContent=batch.count===1?'Fichier reçu et vérifié':`${batch.count} fichiers reçus et vérifiés`;$('doneInfo').textContent=`${fmt(totalReceived)} reçus directement · CRC32 validé`;$('doneCard').classList.remove('hidden');renderDownloads();stat('ok','Transfert terminé','Réception complète et intégrité validée.');await wakeOff()}
async function onMessage(e){if(typeof e.data==='string'){let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='batch-meta'){const same=batch&&batch.totalSize===m.totalSize&&batch.count===m.count;batch=m;renderBatch();stat('ok','Sélection trouvée',accepted?'NOVA prépare automatiquement la reprise.':'Vérifie la sélection puis accepte.');if(accepted){const off=await getOffsets();totalReceived=off.reduce((a,b)=>a+b,0);base=totalReceived;started=performance.now();$('fileCard').classList.add('hidden');send({type:'resume-ready',offsets:off});guard(true,'Connexion rétablie : NOVA reprend depuis les données déjà conservées.')}else if(!same){results=[];handles.clear();totalReceived=0}}else if(m.type==='file-start')await beginFile(m);else if(m.type==='file-end'){const check=await finishFile(m);send({type:'file-ack',index:m.index,...check})}else if(m.type==='batch-done')await done();else if(m.type==='cancel'){guard(false);stat('err','Transfert annulé','L’expéditeur a annulé le transfert.')}return}if(!current)return;const data=e.data instanceof ArrayBuffer?e.data:await e.data.arrayBuffer(),u=new Uint8Array(data);crc=crcUp(crc,u);received+=data.byteLength;totalReceived+=data.byteLength;if(writer)chain=chain.then(()=>writer.write(data));progress()}
$('accept').addEventListener('click',accept);window.addEventListener('beforeunload',e=>{if(accepted&&!finished){e.preventDefault();e.returnValue=''}});window.addEventListener('pagehide',()=>{guard(false);try{ch?.close();pc?.close();ws?.close()}catch{}for(const u of urls)try{URL.revokeObjectURL(u)}catch{}wakeOff()});mobile();try{conn()?.addEventListener?.('change',mobile)}catch{}ui();connect(false);
})();